apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-lookup
  description: Artist Lookup updated!
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Users1
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
  annotations:
    backstage.io/source-template: template:default/springboot-template
    backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']


---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: this is team-a
spec:
  type: team
  profile:
    displayName: Infrastructure
    email: team-a@carrier.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  members: [albert]
