apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terroir-tracking-web2
  description: Find where your juice comes from
spec:
  type: service
  lifecycle: production
  owner: tracking-team
