apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: v1beta3-demo
  title: Test Action template
  description: scaffolder v1beta3 template demo
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Authenticaion
      description: Provide authentication for the resource
      required:
        - username
        - password
        - owner
      properties:
        username:
          title: Simple text input
          type: string
          description: Description about input
          maxLength: 8
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
          ui:autofocus: true
          ui:help: 'Hint: additional description...'
   
        password:
          type: string
          title: password
          ui:field: Secret
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]
        multiline:
            title: Text area input
            type: string
            description: Insert your multi line string
            ui:widget: textarea
            ui:options:
              rows: 10
            ui:help: 'Hint: Make it strong!'
            ui:placeholder: |
              apiVersion: backstage.io/v1alpha1
                kind: Component
                metadata:
                  name: backstage
                spec:
                  type: library
                  owner: CNCF
                  lifecycle: experimental
        volume_type:
          title: Volume Type
          type: string
          description: The volume type to be used
          default: gp2
          enum:
            - gp2
            - gp3
            - io1
            - io2
            - sc1
            - st1
            - standard
          enumNames:
            - 'General Purpose SSD (gp2)'
            - 'General Purpose SSD (gp3)'
            - 'Provisioned IOPS (io1)'
            - 'Provisioned IOPS (io2)'
            - 'Cold HDD (sc1)'
            - 'Throughput Optimized HDD (st1)'
            - 'Magnetic (standard)'
        envname:
          title: Select environments
          type: array
          items:
            type: string
            enum:
              - production
              - staging
              - development
          uniqueItems: true
          ui:widget: checkboxes
  steps:
    - id: setupAuthentication
      action: auth:create
      input:
        # make sure to use ${{ secrets.parameterName }} to reference these values
        username: ${{ parameters.username }}
        password: ${{ secrets.password }}
        owner: ${{ parameters.owner}}